target("test")
    set_kind("binary")
    add_files("src/*.cpp")
    after_load(function (target)
        import("core.project.project")
        local t = target:clone()
        t:name_set("test2")
        t:add("defines", "TEST2")
        project.target_add(t)
    end)

