
target("dep1")
    set_kind("static")
    add_files("src/*.c") 
    add_includedirs("inc1", {public = true})
    add_defines("TEST1", {public = true})

target("dep2")
    set_kind("shared")
    add_deps("dep1")
    add_files("src/*.c") 
    add_includedirs("inc2", {interface = true})
    add_defines("TEST2", {interface = true})

target("dep3")
    set_kind("static")
    add_files("src/*.c") 
    add_includedirs("inc3")

target("dep4")
    set_kind("static")
    add_files("src/*.c") 
    add_includedirs("inc4", {public = true})
    add_defines("TEST4", {public = true})

target("demo")
    set_kind("binary")
    add_deps("dep2", "dep3")
    add_deps("dep4", {inherit = false})
    add_files("src/*.c") 
