# prefix
include $(PRO_DIR)/prefix.mak

# module name
NAMES 					= lcurses

# module type
lcurses_TYPE 			= LIB

# config
lcurses_CONFIG 			= n

# core files
lcurses_C_FILES 		+= lcurses
										
# includes
lcurses_INC_DIRS  		+= ../luajit/src

# suffix
include $(PRO_DIR)/suffix.mak

