set_version("1.0.0")
add_rules("mode.debug", "mode.release")

includes("@builtin/xpack")

target("test")
    set_kind("binary")
    add_files("src/*.cpp")

xpack("test")
    set_formats("nsis")
    set_description("hello")
    add_targets("test")
    set_basename("test-$(plat)-$(arch)-v$(version)")
    add_installfiles("src/assets/*.png")
    set_installdir("resources")
    set_iconfile("src/assets/xmake.ico")
    on_installcmd(function (package, batchcmds)
        batchcmds:cp("src/assets/*.txt", "resources/", {rootdir = "src"})
        batchcmds:mkdir("stub")
    end)
    on_uninstallcmd(function (package, batchcmds)
        batchcmds:rmdir("resources")
        batchcmds:rmdir("stub")
    end)

