# this is a SRPM spec file,
# it is autogenerated by the xmake build system.
# do not edit by hand.

Name:       ${PACKAGE_NAME}
Version:    ${PACKAGE_VERSION}
Release:    1%{?dist}
Summary:    ${PACKAGE_TITLE}

License:    ${PACKAGE_LICENSE}
URL:        ${PACKAGE_HOMEPAGE}
Source0:    ${PACKAGE_ARCHIVEFILE}

BuildRequires: gcc
BuildRequires: gcc-c++

%description
${PACKAGE_DESCRIPTION}

%prep

%build

%install
${PACKAGE_INSTALLCMDS}

%check

%files

%changelog
* ${PACKAGE_DATE} ${PACKAGE_MAINTAINER} - ${PACKAGE_VERSION}-1
- Update to ${PACKAGE_VERSION}

