# this is a SRPM spec file,
# it is autogenerated by the xmake build system.
# do not edit by hand.

Name:       ${PACKAGE_NAME}
Version:    ${PACKAGE_VERSION}
Release:    1%{?dist}
Summary:    ${PACKAGE_TITLE}

License:    Apache-2.0 AND LicenseRef-Fedora-Public-Domain AND BSD
URL:        ${PACKAGE_HOMEPAGE}
Source0:    https://github.com/xmake-io/xmake/releases/download/v%{version}/%{name}-v%{version}.tar.gz

BuildRequires: gcc
BuildRequires: gcc-c++
BuildRequires: xmake

%description
${PACKAGE_DESCRIPTION}

%prep
%autosetup -n %{name}-%{version} -p1

%build
xmake

%install
xmake install

%check

%files

%changelog

