add_rules("mode.debug", "mode.release")

target("test")
    set_kind("binary")
    add_files("src/*.cpp")
    add_defines("TEST1=\"hello\"")
    add_defines("TEST2=\"hello xmake\"")
    add_defines("TEST3=3")
    add_cxflags("-DTEST4=\"hello\"")
    add_cxflags("-DTEST5=\"hello xmake\" -DTEST6=3")
