add_rules("mode.release", "mode.debug")
add_requires("python 3.x")
add_requires("nlohmann_json")

target("example")
    add_rules("swig.cpp", {moduletype = "python"})
    add_files("src/example.i", {scriptdir = "share"})
    add_files("src/example.cpp")
    add_packages("python")
    add_packages("nlohmann_json")