package("foo")
    add_deps("zlib >=1.2.13")
    set_policy("package.install_locally", true)
    on_install(function () end)
package_end()

package("bar")
    add_deps("zlib 1.2.x")
--    add_deps("libpng dev")
--    add_deps("boost", {system = false, configs = {}})
    set_policy("package.install_locally", true)
    on_install(function () end)
package_end()

package("zoo")
--    add_deps("libpng master")
--    add_deps("boost", {system = false, configs = {zlib = true}})
    set_policy("package.install_locally", true)
    on_install(function () end)
package_end()

package("test")
    add_deps("foo", "bar", "zoo")
    set_policy("package.install_locally", true)
    on_install(function () end)
package_end()

add_requires("test")
--add_requireconfs("**.boost", {override = true, configs = {zlib = false}})

target("test")
    set_kind("binary")
    add_files("src/*.c")
    add_packages("test")
