
function test_workdir(t)
    os.tryrm("test")
    os.tryrm("build")
    os.tryrm("build2")
    os.tryrm(".xmake")
    os.exec("xmake create test")
    os.exec("xmake config -P test")
    os.exec("xmake")
    t:require(os.isdir("build"))
    t:require(os.isdir(".xmake"))
    t:require_not(os.isdir("test/build"))
    t:require_not(os.isdir("test/.xmake"))
    os.exec("xmake config -o build2")
    os.exec("xmake")
    t:require(os.isdir("build2"))
    os.tryrm("build")
    os.tryrm("build2")
    os.tryrm(".xmake")
    os.cd("test")
    os.exec("xmake create -P subtest")
    os.cd("subtest")
    os.exec("xmake config -P .")
    os.exec("xmake")
    t:require(os.isdir("build"))
    t:require(os.isdir(".xmake"))
    t:require_not(os.isdir("../build"))
    t:require_not(os.isdir("../.xmake"))
    t:require_not(os.isdir("../../build"))
    t:require_not(os.isdir("../../.xmake"))
end

