rule("test")
    set_extensions(".md")
    on_config(function (target)
        print("test: config %s", target:name())
    end)
    on_build_file(function(target, sourcefile)
        print("test: build %s", sourcefile)
    end)
    after_clean(function (target)
        print("test: clean")
    end)
