#!/bin/bash

# install fpm
# brew install gnu-tar
# gem install --no-ri --no-rdoc fpm

# version
version=2.1.3

# arch
arch=i386
if [ `getconf LONG_BIT` == "64" ]; then
    arch=x86_64
fi

# build xmake core
cd ./core
make f DEBUG=n
make r
cd -

# make xmake wrapper
echo "#/!bin/bash
export XMAKE_PROGRAM_DIR=/usr/local/share/xmake
/usr/local/share/xmake/xmake \"\$@\"
" > /tmp/xmake.sh
chmod 755 /tmp/xmake.sh

# make dep package using fpm
fpm -s dir -t osxpkg -n xmake -v $version -m "<waruqi@gmail.com>" --description="A make-like build utility based on Lua" --license=LICENSE.md \
        xmake=/usr/local/share/ \
        core/bin/demo.pkg/bin/macosx/$arch/demo.b=/usr/local/share/xmake/xmake \
        /tmp/xmake.sh=/usr/local/bin/xmake


