#!/bin/bash

# install fpm
# brew install gnu-tar
# gem install --no-ri --no-rdoc fpm

# check
if [ $# -lt 2 ]; then
    echo "Usage: ./scripts/makepkg [rpm|deb|oscpkg|pacman] [version]"
    exit
fi

# target
target=$1

# version
version=$2

# arch
arch=i386
if [ `getconf LONG_BIT` == "64" ]; then
    arch=x86_64
fi

# platform
plat=linux
if [ `uname` == "Darwin" ]; then
    plat=macosx
fi

# build xmake core
cd ./core
make f DEBUG=n
make r
cd -

# make xmake wrapper
echo "#/!bin/bash
export XMAKE_PROGRAM_DIR=/usr/local/share/xmake
/usr/local/share/xmake/xmake \"\$@\"
" > /tmp/xmake.sh
chmod 755 /tmp/xmake.sh

# make dep package using fpm
fpm -s dir -t $target -n xmake -v $version -m "<waruqi@gmail.com>" --description="A make-like build utility based on Lua" --license=LICENSE.md \
        xmake=/usr/local/share/ \
        core/bin/demo.pkg/bin/$plat/$arch/demo.b=/usr/local/share/xmake/xmake \
        /tmp/xmake.sh=/usr/local/bin/xmake


