set_project("link_libs")
add_rules("mode.debug", "mode.release")

add_requires("zlib", {system = false})
add_requires("stb", {system = false})

target("headers")
    set_kind("headeronly")
    add_files("headers/*.h")
    add_includedirs("headers")

target("executablestatic")
    set_kind("binary")
    add_files("mainlib.nim")
    add_deps("staticlib")
    add_packages("zlib", "stb")
    add_syslinks("pthread", "m")

target("executableshared")
    set_kind("binary")
    add_files("maindll.nim")
    add_deps("sharedlib")
    add_syslinks("pthread", "m")

target("staticlib")
    set_kind("static")
    add_files("static.nim")
    add_includedirs("inc")
    add_headerfiles("inc/*.h")
    add_syslinks("pthread", "m")
    add_deps("headers")

target("sharedlib")
    set_kind("shared")
    add_files("shared.nim")
    add_includedirs("inc")
    add_headerfiles("inc/*.h")
    add_syslinks("pthread", "m")
    add_deps("headers")
