version: "1.0.{build}"

platform:
  - Win32
  - x64

image:
  - Visual Studio 2013
  - Visual Studio 2015
  - Visual Studio 2017

configuration:
  - Debug
  - Release

init:
  - ps: Invoke-Expression (Invoke-Webrequest 'https://raw.githubusercontent.com/tboox/xmake/master/scripts/get.ps1' -UseBasicParsing).Content
  - cmd: xmake --version
  - cmd: msbuild /version

branches:
  only:
    - master
    - dev

install:
  - git submodule update --init --recursive

before_build:
  - cmd: if %platform%==x64 xmake f -a x64
  - cmd: if %configuration%==Debug xmake f -m debug
  - cmd: if %configuration%==Release xmake f -m release

build_script:
  - cmd: xmake -v

test_script:
  - cmd: xmake check
