# prefix
include $(PRO_DIR)/prefix.mak

# module name
NAMES 					= sv

# module type
sv_TYPE 				= LIB

# config
sv_CONFIG 				= n

# core files
sv_C_FILES 				+= \
						src/comp \
						src/id \
						src/num \
						src/range \
						src/semvers \
						src/utils \
						src/version

# includes
sv_INC_DIRS  			+= include

										
# suffix
include $(PRO_DIR)/suffix.mak

