# Setup
title:        xmake
tagline:      A make-like build utility based on Lua
tagline-cn:   一个基于Lua的轻量级自动构建工具
keywords:     make,makefile,build,lua,cross-compile,linux
keywords-cn:  make,makefile,构建工具,编译工具,lua,跨平台,跨平台开发,linux,交叉编译
baseurl:      ""
paginate:     1

# About/contact
author:
  name:       waruqi
  url:        http://www.tboox.org 

#Others
markdown: kramdown

# multiple-languages
gems:               ['jekyll-paginate', 'jekyll-multiple-languages']
languages:          ['en', 'cn']
language_default:   'en'
