#!/bin/bash

function exe_cmd() 
{
    echo $1
    eval $1
}

# build sites
exe_cmd "jekyll build"
if [ ! -d '_site' ];then
    echo "not content to be published!"
    exit
fi

# install sites
exe_cmd "cp -r _site/cn .."
exe_cmd "cp -r _site/assets/* ../assets/"
exe_cmd "cp -r _site/pages .."
exe_cmd "cp _site/index.html ../landing.html"
exe_cmd "rm -rf _site"

